### ISSUE TITLE
encodeHex question

### ISSUE THREAD

**Issue by pgherveou** [ivanakimov/hashids.node.js#19]
quick stupid question

on line https://github.com/ivanakimov/hashids.node.js/blob/master/lib/hashids.js#L163
why do we  write 
```js
numbers[i] = parseInt("1" + numbers[i], 16)
```
instead of just 
```js
numbers[i] = parseInt(numbers[i], 16)
```

**Comment by ivanakimov** [comment]
When breaking down a large hex string, some chunks might end up with leading zeros. Since the next step is to convert them to integers, we'll lose those zeros. And since we need to keep them, we simply prepend a 1.

**Comment by pgherveou** [comment]
Thks for the clarifications!
