### ISSUE TITLE
Add - and _ to the default alphabet

### ISSUE THREAD

**Issue by tkrotoff** [ivanakimov/hashids.node.js#20]
Default alphabet currently is [`abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890`](https://github.com/ivanakimov/hashids.node.js/blob/1.0.2/lib/hashids.js#L39) (base62).

YouTube video ids also use `-` and `_` (empirical: Google does not go into details on this).

The [URI RFC 3986](https://tools.ietf.org/html/rfc3986#section-2.3) list `ALPHA / DIGIT / "-" / "." / "_" / "~"` as unreserved characters.

`~` seems to be ["unsafe because gateways and other transport agents are known to sometimes modify such characters"](https://perishablepress.com/stop-using-unsafe-characters-in-urls/) and ["has special meaning in some file system environments"](https://tools.ietf.org/html/rfc4648#section-5).

`.` might be confusing because it is used for domain names (imagine an URL like youtube.com/jNQXAC9.com) and "some file system environments do not permit multiple '.' in a filename".

So I suggest to add `-` and `_` to the current default alphabet => same alphabet as [base64url](https://tools.ietf.org/html/rfc4648#section-5).

**Comment by ivanakimov** [comment]
Thanks for the suggestion, @tkrotoff. This is of course with an assumption that hashids will be used in URLs only; otherwise, strictly alphanumeric alphabet might be easier to deal with. I'll mark this as a feature request; anyone else, feel free to +1.

**Comment by lucdetellis** [comment]
Adding this as a feature seems unnecessary because you can just specify a custom alphabet.
For example:
```javascript
var Hashids = require('hashids');
var hashids = new Hashids('salt', 8, 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-_');
console.log(hashids.encode(1)); // -> 'v2qK-qAV'
```

**Comment by ivanakimov** [comment]
Closing. Doesn't look like much interest in this feature. Plus might be more headache for existing implementation if they upgrade and find extra characters that they weren't expecting. 

Please use custom alphabet parameter in the constructor instead.
