### ISSUE TITLE
Alphabets of fewer than 16 chars

### ISSUE THREAD

**Issue by irakliy81** [ivanakimov/hashids.node.js#21]
This is just a question: is there a reason why alphabet length cannot be less than 16 characters? 

Specifically, I would like to use numeric-only alphabet ("1234567890") to obfuscate sequential IDs but with the current restriction this does not seem to be possible.

Thanks!

**Comment by ivanakimov** [comment]
https://github.com/ivanakimov/hashids.js/issues/21

**Comment by irakliy81** [comment]
Thank you!
