### ISSUE TITLE
Allow generating hashids consisting of only uppercase letters.

### ISSUE THREAD

**Issue by UlyssesAlves** [ivanakimov/hashids.node.js#24]
The requirements of a project I'm working at have changed and now the hashids must be generated as **uppercase letters only**, without numbers or special characters of any sort. 

This is because the hashids will now be used as promotional codes, and the project manager finds it's easier for the end user to remember his/her promotional codes when it is composed only of letters, and he also finds it confusing for the user if promotional codes ABCDEFG is diferent from, say, AbCdEFg. So the hashid now needs to be composed only of uppercase letters, and also, it has to be six digits (or letters, in this case) long.

Is this a thing I can implement with hashids, or will I have to use another lib to comply with these new requirements?

If it is possible to do with current version of hashids, please, how can I implement this in my code?

**Comment by pdehaan** [comment]
https://github.com/ivanakimov/hashids.node.js#specifying-custom-id-alphabet has a section on specifying a custom ID alphabet:

```js
const Hashids = require("hashids");
const hashids = new Hashids("this is my salt", 6, "ABCDEFGHJKLMNPQRSTUVWXYZ");

var id = hashids.encode(40, 94089, 94121);
console.log(id); // QDYFGXEKZCQEARB
```

Not sure how you can create an `id` that is _exactly_ 6 characters long.

**Comment by UlyssesAlves** [comment]
@pdehaan The second parameter to the Hashids constructor function is thus the minimum length for the generated hashids, and not the actual exact length?

**Comment by ivanakimov** [comment]
@UlyssesAlves yes, the second parameter is the **minimum** length -- it's simply used as a padding feature only. There is no guarantee that your generated ids will always be exactly 6 characters long, because there's no way to fit an infinite number of integers into 6 chars. Eventually it will overflow.
