### ISSUE TITLE
Server silently fails to start when creating hashid with only numbers

### ISSUE THREAD

**Issue by brianchaan** [ivanakimov/hashids.node.js#25]
Really weird error that I wanted to pass along. I had previously been using a hashid like this:

```new Hashids('test', 10, "0123456789ABCDEF")```

which worked fine. When I changed to this:

```new Hashids('test', 10, "0123456789")```

my server would simply not start up and hang forever. Of course I was doing lots of stuff at the time and it took me forever to figure out that this was the culprit. I have no idea why this would cause a problem, but maybe some error checking would be helpful here.

**Comment by ivanakimov** [comment]
Hm, the alphabet itself shouldn't cause anything crazy (especially one this basic). Are you sure you didn't miss a callback somewhere else in your code or something and it was just waiting?

**Comment by brianchaan** [comment]
I did a little more debugging on this and it actually does throw an error:

```error: alphabet must contain at least 16 unique characters```

So I guess the fault is in the error handling of my server startup and not with your library. Thanks for the quick interest and support.
